<a href="https://colab.research.google.com/github/GautamChy/Data-Science/blob/main/32_logistic_regression(Binary_Classification).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from sklearn.datasets import load_iris

In [21]:
dataset = load_iris()

In [22]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [23]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [24]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [25]:
import pandas as pd
import numpy as np

In [26]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)

In [28]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [29]:
# create new target column and put  dictionary target value
df['target'] = dataset.target

In [30]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [31]:
df['target'].value_counts()

,count
target,
0,50
1,50
2,50


In [32]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Binary Classification

#  Categorical Variables and Continuous Variables

## 1. Categorical Variable
# NOTE: Output ma categorical variable vaako bela LOGISTIC REGRESSION use hunxa

# NOTE : Categorical Variable mainly used in Logistic Regression

A **categorical variable** puts observations into **groups or categories**. The values represent types or labels rather than amounts.

### Examples:
- Gender: Male / Female / Other
- Blood group: A / B / AB / O
- Smoker: Yes / No
- Education: School / College / University
- Eye colour: Brown / Blue / Green

👉 **Think:** "Which group?"

---

## Simple Example

Suppose we study whether a person has a disease:

| Variable | Type | Example |
|---|---|---|
| Age | Continuous | 45.5 years |
| Weight | Continuous | 72.3 kg |
| Blood pressure | Continuous | 125.6 |
| Gender | Categorical | Male |
| Smoker | Categorical | Yes |
| Disease | Categorical | Yes/No |

---

## Variables in Logistic Regression

In **logistic regression**, the **dependent variable** is commonly categorical, usually **Yes/No or 0/1**.

The **independent variables** can be:

- Continuous variables
- Categorical variables
- Or a mixture of both

### Example:

**Dependent variable (Y):**
- Disease → Yes/No

**Independent variables (X):**
- Age → Continuous
- Weight → Continuous
- Gender → Categorical
- Smoker → Categorical



## 2. Continuous Variable

A **continuous variable** is a value that can take many possible numerical values, including decimals.

### Examples:
- Height: 170.5 cm
- Weight: 68.7 kg
- Age: 25.5 years
- Temperature: 36.8°C
- Income: £2,450.75

👉 **Think:** "How much?" or "How many?"

### In simple words:

> Logistic regression can use continuous and categorical independent variables to predict a categorical outcome.

---



In [34]:
df['target'] != 2

,target
0,True
1,True
2,True
3,True
4,True
...,...
145,False
146,False
147,False
148,False


In [35]:
df_copy = df[df['target'] !=2]

In [36]:
df_copy.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [37]:
df_copy.shape

(100, 5)

In [38]:
df_copy['target'].value_counts()

,count
target,
0,50
1,50


In [39]:
df_copy.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1


In [41]:
df_copy['target']

,target
0,0
1,0
2,0
3,0
4,0
...,...
95,1
96,1
97,1
98,1


In [42]:
df_copy.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [44]:
df_copy['target'].unique()

array([0, 1])

In [45]:
df_copy['target'].value_counts()

,count
target,
0,50
1,50


In [46]:
df_copy

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


#  Dependent and Independent

In [47]:
# Independent
x = df_copy.iloc[:,:-1]

In [48]:
x

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
95,5.7,3.0,4.2,1.2
96,5.7,2.9,4.2,1.3
97,6.2,2.9,4.3,1.3
98,5.1,2.5,3.0,1.1


In [49]:
# Dependent
y = df_copy.iloc[:,-1]

In [50]:
y

,target
0,0
1,0
2,0
3,0
4,0
...,...
95,1
96,1
97,1
98,1


In [51]:
from sklearn.linear_model import LogisticRegression

In [54]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.33, random_state = 121)

In [55]:
X_train

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
53,5.5,2.3,4.0,1.3
76,6.8,2.8,4.8,1.4
48,5.3,3.7,1.5,0.2
5,5.4,3.9,1.7,0.4
59,5.2,2.7,3.9,1.4
...,...,...,...,...
65,6.7,3.1,4.4,1.4
95,5.7,3.0,4.2,1.2
8,4.4,2.9,1.4,0.2
85,6.0,3.4,4.5,1.6


In [57]:
X_train.shape

(67, 4)

In [56]:
X_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
82,5.8,2.7,3.9,1.2
38,4.4,3.0,1.3,0.2
23,5.1,3.3,1.7,0.5
98,5.1,2.5,3.0,1.1
18,5.7,3.8,1.7,0.3
22,4.6,3.6,1.0,0.2
20,5.4,3.4,1.7,0.2
15,5.7,4.4,1.5,0.4
97,6.2,2.9,4.3,1.3
29,4.7,3.2,1.6,0.2


In [58]:
X_test.shape

(33, 4)

In [59]:
y_train

,target
53,1
76,1
48,0
5,0
59,1
...,...
65,1
95,1
8,0
85,1


In [60]:
y_train.shape

(67,)

In [61]:
y_test

,target
82,1
38,0
23,0
98,1
18,0
22,0
20,0
15,0
97,1
29,0


In [62]:
y_test.shape

(33,)

In [63]:
classifier = LogisticRegression()

In [64]:
classifier

LogisticRegression()

In [66]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [68]:
## prediction
y_pred = classifier.predict(X_test)

In [69]:
y_pred

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1])

In [70]:
list(y_test)

[1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1]

In [71]:
# checking the probability in X_test
classifier.predict_proba(X_test)

array([[0.03278461, 0.96721539],
       [0.97553608, 0.02446392],
       [0.92615997, 0.07384003],
       [0.21919524, 0.78080476],
       [0.94306035, 0.05693965],
       [0.99071675, 0.00928325],
       [0.93827705, 0.06172295],
       [0.9729971 , 0.0270029 ],
       [0.01305752, 0.98694248],
       [0.95597937, 0.04402063],
       [0.92813985, 0.07186015],
       [0.97350752, 0.02649248],
       [0.0686867 , 0.9313133 ],
       [0.94297103, 0.05702897],
       [0.92786398, 0.07213602],
       [0.94957608, 0.05042392],
       [0.03964232, 0.96035768],
       [0.0249099 , 0.9750901 ],
       [0.97852632, 0.02147368],
       [0.97880246, 0.02119754],
       [0.97631447, 0.02368553],
       [0.00467597, 0.99532403],
       [0.96018007, 0.03981993],
       [0.9450928 , 0.0549072 ],
       [0.97177751, 0.02822249],
       [0.96874356, 0.03125644],
       [0.02709121, 0.97290879],
       [0.95152867, 0.04847133],
       [0.96434738, 0.03565262],
       [0.96906398, 0.03093602],
       [0.

# Confusion matrix, accuracy score, classification report

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [77]:
print(confusion_matrix(y_test, y_pred))  # y_test is original and y_predict is after prediction

[[22  0]
 [ 0 11]]


In [80]:
print(accuracy_score(y_test,y_pred))

1.0


In [81]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        11

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



# Hyperparameter Tuning
- Hyperparameter tuning = trying different model settings to find the settings that give the best performance.

In [83]:
# GridSearchCV is a tool in Python's scikit-learn that helps you find the best hyperparameters for a machine learning model.
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [84]:
parameters = {
    'penalty' : ['11','12','elasticnet',None],
    'dual' : [True, False],
    'C' : [1,10,20,30,40,50],
    'max_iter' : [100,200,300,1000,10000]
}

In [95]:
clf = GridSearchCV(classifier, param_grid = parameters)

In [96]:
clf # here data is not fitted.

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30, 40, 50], 'dual': [True, False],
                         'max_iter': [100, 200, 300, 1000, 10000],
                         'penalty': ['11', '12', 'elasticnet', None]})

In [97]:
## Splitting of train data to validation data, and here data is fitted.
clf.fit(X_train, y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30, 40, 50], 'dual': [True, False],
                         'max_iter': [100, 200, 300, 1000, 10000],
                         'penalty': ['11', '12', 'elasticnet', None]})

In [106]:
# selecting best parameters
clf.best_params_

{'C': 1, 'dual': False, 'max_iter': 100, 'penalty': None}

In [107]:
clssifier = LogisticRegression(C = 1, penalty = '12', max_iter = 100, dual = False)

In [108]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [109]:
## prediction
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[22  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        11

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [119]:
## Randomized Search CV
from sklearn.model_selection import RandomizedSearchCV

In [120]:
random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions = parameters)

In [121]:
random_clf.fit(X_train, y_train)

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20, 30, 40, 50],
                                        'dual': [True, False],
                                        'max_iter': [100, 200, 300, 1000,
                                                     10000],
                                        'penalty': ['11', '12', 'elasticnet',
                                                    None]})

In [134]:
random_clf.best_params_

{'penalty': None, 'max_iter': 300, 'dual': False, 'C': 10}

In [135]:
# making classifier model
classifier = LogisticRegression(C = 40, penalty = None, max_iter = 1000)

In [136]:
classifier

LogisticRegression(C=40, max_iter=1000, penalty=None)

In [137]:
classifier.fit(X_train, y_train)

LogisticRegression(C=40, max_iter=1000, penalty=None)

In [139]:
## prediction
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[22  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      1.00      1.00        11

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [140]:
# Import pickle for saving and loading the model
import pickle

In [141]:
# Filepath for saving the model
pickle_file = 'logistic.plk'

In [144]:
# Save the trained model to a pickle file
with open(pickle_file, 'wb') as file:
  pickle.dump(classifier,file)

In [145]:
print(f'model saved to {pickle_file}')

model saved to logistic.plk


In [147]:
# Load the model from the pickle file
with open(pickle_file, 'rb') as file:
  loaded_model = pickle.load(file)

In [149]:
# Test the loaded model with predictions
y_pred_loaded = loaded_model.predict(X_test)
print(y_pred_loaded)

[1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1]


In [151]:
x.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [152]:
y.head()

,target
0,0
1,0
2,0
3,0
4,0


In [153]:
loaded_model.predict([[5.1, 3.5, 1.4, 0.2]])

array([0])

In [154]:
loaded_model.predict([[3.5,4.2,5.5,6.3]])

array([1])