<a href="https://colab.research.google.com/github/GautamChy/Data-Science/blob/main/34_KNN_Algorithm_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classifier

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from sklearn.datasets import make_classification
# sklearn library ko dataset module bataw make_classification leko.
x,y  = make_classification(
    n_samples= 1000, # 1000 otaw row vaako sample banyo
    n_features= 3, #  total independent features i.e columns
    n_classes= 2, # It means multiclassification, 0 and 1. i.e binary target/label
    n_redundant= 1, # A column, B column ko combination banyeraw aako value C ma. i,e = A 10, C = 20 , C = A + B

)
# X = Independet, y = dependent
# Independent means = Input, dependent means = output

In [ ]:
x

array([[ 0.67645653, -0.04426119,  0.83913583],
       [-1.04959595,  2.39958211,  2.34814165],
       [-1.14655267,  1.87756932,  1.40047195],
       ...,
       [ 3.54138878, -2.40385675,  0.99151997],
       [-0.66034674,  1.58795807,  1.59989725],
       [-0.77237478,  0.25072152, -0.64463659]])

In [ ]:
x.shape

(1000, 3)

In [ ]:
y

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,

In [ ]:
y.shape

(1000,)

In [ ]:
# train model
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.33, random_state = 42)

In [ ]:
# Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier = KNeighborsClassifier()


In [ ]:
classifier

KNeighborsClassifier()

In [ ]:
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
# model predicted data
y_pred

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [ ]:
# original data
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [ ]:
# for classifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))       # output = 0.97 = It means 1000 ota maa 970 data predict gardey ko xa.It is good.
print(classification_report(y_pred, y_test))

[[162   7]
 [  2 159]]
0.9727272727272728
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       169
           1       0.96      0.99      0.97       161

    accuracy                           0.97       330
   macro avg       0.97      0.97      0.97       330
weighted avg       0.97      0.97      0.97       330



In [ ]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [ ]:
parameters = {
  'n_neighbors' : list(range(30)),  # which tests K values from 1 to 29.
  'p' : [1,2]                          # p determines the distance calculation used by KNN.
                                       #p = 1 → Manhattan distance.
                                       #p = 2 → Euclidean distance.
}
                                    # For KNN, n_neighbors means K, the number of neighbors used to make a prediction.


In [ ]:
clf = GridSearchCV(classifier, param_grid = parameters)

In [ ]:
## Splitting of train data to validation data
clf.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29],
                         'p': [1, 2]})

In [ ]:
clf.best_params_

{'n_neighbors': 3, 'p': 2}

In [ ]:
classifier = KNeighborsClassifier(n_neighbors =  6, p = 2)

In [ ]:
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
## Prediction
y_pred = classifier.predict(x_test)  # y_pred => model ley predict garey ko data. x_test => original data
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[163   9]
 [  1 157]]
0.9696969696969697
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       172
           1       0.95      0.99      0.97       158

    accuracy                           0.97       330
   macro avg       0.97      0.97      0.97       330
weighted avg       0.97      0.97      0.97       330



In [ ]:
# Import pickle for saving and loading the model
import pickle

In [ ]:
# Filepath for saving the model
knn_file = 'knn.plk'

In [ ]:
# Save the trained model to a pickle file
with open(knn_file, 'wb') as file:
  pickle.dump(classifier,file)

In [ ]:
print(f'model saved to {knn_file}')

model saved to knn.plk


In [ ]:
# Load the model from the pickle file
with open(knn_file, 'rb') as file:
  loaded_model = pickle.load(file)

In [ ]:
# Test the loaded model with predictions
y_pred_loaded = loaded_model.predict(x_test)
print(y_pred_loaded)

[1 0 1 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0
 1 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0
 1 0 0 1 0 1 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0
 1 1 1 0 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1
 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0
 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0
 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1
 0 1 1 1 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 1 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1
 1 1 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0]


In [ ]:
loaded_model.predict([[1,2,3]])

array([0])

In [ ]:
loaded_model.predict([[4,2,1]])

array([1])